{% set version = "0.0.8" %}
{% set build = 0 %}

package:
  name: torchonn
  version: {{ version }}

source:
  path: .
  git_rev: v0.0.8
  git_url: https://github.com/JeremieMelo/pytorch-onn.git

build:
  number: {{ build }}
  noarch: python
  script: {{ PYTHON }} setup.py install --user clean

# test:
#   imports:
#     - torchonn

requirements:
  # host:
  #   - python # this enables conda to use PYTHON environment variable
  build:
    - python=3.10
    - pip >=21.0.1
    - setuptools >=52.0.0
    - numpy >=1.19.2
    - torchvision
    - tqdm
    - pytorch=2.3.0
    - pytorch-cuda=11.8
    - matplotlib
    - tensorflow-gpu=2.14.0
    - svglib 
    - scipy >=1.5.4
    - scikit-learn >=0.24.1
    - pyyaml
    - multimethod
    - scienceplots
    - mmengine=0.10.4
    - mmcv=2.1.0
  run:
    - python >=3.10
    - numpy >=1.19.2
    - torchvision
    - tqdm
    - pytorch=2.3.0
    - pytorch-cuda=11.8
    - matplotlib
    - tensorflow-gpu=2.14.0
    - svglib 
    - scipy >=1.5.4
    - scikit-learn >=0.24.1
    - pyyaml
    - multimethod
    - scienceplots
    - mmengine=0.10.4
    - mmcv=2.1.0

about:
  home: https://github.com/JeremieMelo/pytorch-onn
  license: MIT
  summary: A library for python/pytorch ONN training

extra:
  recipe-maintainers:
    - jiaqigu